# Generated by Django 4.2.1 on 2023-06-07 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auctioncategory_auctionlisting_bid_comment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AuctionCategory',
            new_name='Category',
        ),
        migrations.RenameModel(
            old_name='AuctionListing',
            new_name='Listing',
        ),
    ]
