# Generated by Django 4.2.1 on 2023-06-08 15:53

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_rename_auctioncategory_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='post_data',
        ),
        migrations.RemoveField(
            model_name='listing',
            name='price',
        ),
        migrations.AddField(
            model_name='bid',
            name='bid_value',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AddField(
            model_name='bid',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='listing',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='bid',
            name='user',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='bids', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='text',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='listing',
            name='bid_starting_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='category',
            field=models.CharField(choices=[('No Selection', 'No Selection'), ('Clothing and Fashion', 'Clothing and Fashion'), ('Toys and Games', 'Toys and Games'), ('Electronics', 'Electronics'), ('Home and Kitchen', 'Home and Kitchen'), ('Groceries and Food', 'Groceries and Food'), ('Health and Beauty', 'Health and Beauty'), ('Books and Stationery', 'Books and Stationery'), ('Sports and Fitness', 'Sports and Fitness'), ('Automotive', 'Automotive'), ('Furniture and Decor', 'Furniture and Decor'), ('Pet Supplies', 'Pet Supplies'), ('Tools and Hardware', 'Tools and Hardware'), ('Jewelry and Accessories', 'Jewelry and Accessories'), ('Baby and Maternity', 'Baby and Maternity'), ('Music and Instruments', 'Music and Instruments'), ('Movies and Entertainment', 'Movies and Entertainment'), ('Office Supplies', 'Office Supplies'), ('Travel and Luggage', 'Travel and Luggage'), ('Garden and Outdoor', 'Garden and Outdoor'), ('Arts and Crafts', 'Arts and Crafts')], default='No Selection', max_length=30),
        ),
        migrations.AddField(
            model_name='listing',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='listing',
            name='current_bid_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='listing',
            name='img_url',
            field=models.ImageField(null=True, upload_to='', validators=[django.core.validators.URLValidator]),
        ),
        migrations.AddField(
            model_name='listing',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='owner',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='watchlist',
            name='listings',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlists', to='auctions.listing'),
        ),
        migrations.AddField(
            model_name='watchlist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
