# Generated by Django 4.2.1 on 2023-06-08 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_watchlist_delete_category_remove_listing_post_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='img_url',
        ),
        migrations.AddField(
            model_name='listing',
            name='product_img',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
