# Generated by Django 4.2.1 on 2023-06-09 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_remove_listing_img_url_listing_product_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='product_img',
        ),
        migrations.AddField(
            model_name='listing',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='imgs/'),
        ),
    ]
