# Generated by Django 4.2.1 on 2023-06-10 16:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_watchlistentry_delete_watchlist'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlistentry',
            old_name='listings',
            new_name='listing',
        ),
    ]
