# Generated by Django 4.2.1 on 2023-06-10 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_comment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, default='imgs/profile/default.jpeg', null=True, upload_to='imgs/profile/'),
        ),
    ]
