# Generated by Django 4.2.1 on 2023-06-15 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_listing_closed'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='bid_value',
            new_name='value',
        ),
    ]
