# Generated by Django 4.2.1 on 2023-07-30 02:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_post_associated_post_post_is_comment_delete_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='associated_post',
            new_name='comment_of',
        ),
        migrations.RemoveField(
            model_name='post',
            name='is_comment',
        ),
    ]
