# Generated by Django 4.2.1 on 2023-07-30 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_rename_associated_post_post_comment_of_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comment_of',
        ),
        migrations.CreateModel(
            name='CommentEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='network.post')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='network.post')),
            ],
        ),
    ]
